### ISSUE TITLE
require/prefer DWF-Artifact entries to match DWF assignments?

### ISSUE THREAD

**Issue by zmanion** [distributedweaknessfiling/DWF-Database#13]
What guidance should DWF have concerning assignments and artifacts?

1. Every assignment must (should?) have an artifact, if assignment is pre-public disclosure, artifact creation can happen later? Purge DWF assignments that don't have corresponding artifacts after N days?

2. OK to assign DWFs without ever creating artifacts?

I strongly prefer having artifacts.

**Comment by mprpic** [comment]
+1 for requiring artifacts for each assignment.

**Comment by kurtseifried** [comment]
See email regarding SLA, in principle yes, but also see my email regarding CVE assignments, e.g.:

Some feedback:
INC4: can we better define public/private? E.g. what if a medical device maker plans to use a CVE for an issue that they will then inform ever user of directly? Ditto for aerospace/SCADA/etc.

**Comment by kurtseifried** [comment]
I'm inclined to say a JSON article SHOULD be included once a CVE is in state PUBLIC, but not REQUIRED (in general it should require some exceptional circumstances). Closing unless someone things it needs to be 100% mandatory (and has a plan to deal with public CVEs that don't have JSONs).
