### ISSUE TITLE
Define CSV fields and formats

### ISSUE THREAD

**Issue by kseifriedredhat** [distributedweaknessfiling/DWF-Database#15]
Which CSV fields are single value, which are multiple value?

REPLACED_BY - List of CVE(s), if multiple use a comma to separate.

**Comment by sbunify** [comment]
When you have multiple CVE(s) in REPLACED_BY I'd read it as a SPLIT activity, while a single value typically means that this was a duplicate entry.
Maybe worth to extend this to two CVS fields? E.g.
- one single value field "RELATION" (values: DUPLICATE_OF, SPLIT_TO/_FROM, MERGED_TO/_FROM) - single value
- one field [list of] comma separated RELATED_CVEs

**Comment by sbunify** [comment]
Besides the List of CVE(s), I only see REQUESTER as a second multi-value field - if different people  requested it independently (DUPLICATE) or if researchers/vendors request in a coordinated way

**Comment by kurtseifried** [comment]
Perhaps more simply have "RELATION:CVE", comma separated if multiple are needed, that way you can have multiple if needed (can't imagine a case but you never know). 

as for multiple requestor that should be safe to do with commas to separate

**Comment by sbunify** [comment]
Perfect - that's it, thanks ;-)

**Comment by kurtseifried** [comment]
closing this out as fixed by the latest README.md
