### ISSUE TITLE
data format/relation rules for CSV

### ISSUE THREAD

**Issue by kseifriedredhat** [distributedweaknessfiling/DWF-Database#16]
data rules/relationshipos, e.g. if CVE is state PUBLIC then it must have a published data and assigner/requestor. What other rules do we need/want?

**Comment by kseifriedredhat** [comment]
assigner should always be public

**Comment by attritionorg** [comment]
- Would be slick to track date the ID was requested as well. For metrics types, seeing the delay between that is interesting.
- Title should always be public. Noticed it isn't included in a couple in 2016

**Comment by kurtseifried** [comment]
TITLE is generally only present for CVEs in state PUBLIC, a quick check shows all current PUBLIC have titles so closing.
