### ISSUE TITLE
Numbers from my range used?

### ISSUE THREAD

**Issue by puiterwijk** [distributedweaknessfiling/DWF-Database#2]
It looks like @kurtseifried is using the range DWF-2016-89xxx, which were assigned to me according to the DNA registry?
Is this expected, and should I expect my block to be assigned by others without my knowing, or was this a mistake?

In the case that it's to be expected, that means I would not be able to assign a number until the moment the issue is public, which makes it a lot less useful to me.

**Comment by kurtseifried** [comment]
ah that was a typo I didn't catch, argh. let me fix it up.
