### ISSUE TITLE
DWF-2016-91000 / 91001 - missing artifact(s)

### ISSUE THREAD

**Issue by attritionorg** [distributedweaknessfiling/DWF-Database#20]
Need 0x3d5157636b525761@gmail.com to upload artifacts to support DWF-2016-91000 and DWF-2016-91001.

**Comment by kurtseifried** [comment]
they got renumbered, can you submit artifacts to the current cve entry?

**Comment by attritionorg** [comment]
I don't know what the artifacts were...
