### ISSUE TITLE
What Constitutes a Valid Date Value?

### ISSUE THREAD

**Issue by theall38103** [distributedweaknessfiling/DWF-Database#23]
README.md states that DATE_REQUESTED, DATE_ASSIGNED, and DATE_PUBLIC each should follow the ISO 8601 format and that each can be either just a date or a date and time.

A recent commit (8bd6ed0e62133eed7a41d19359c72f08130a4e4c) making several CVE ids public used a value for DATE_PUBLIC of "2016-07-1", which does not follow the ISO 8601 format since it uses only one digit for the day. [I don't know if the values were truncated or actually refer to July 1st, 2016.]

Further, the documentation doesn't specify whether the date value can be just a year; a year and month; or a year, month, and day. It also doesn't specify whether the value must use extended format ("yyyy-mm-dd") or basic format ("yyyymmdd") or whether either is acceptable. 

It would be helpful if the documentation would clarify what constitutes a valid date value.

**Comment by kurtseifried** [comment]
Typo, corrected. we need the CI stuff sooner rather then later =)
