### ISSUE TITLE
Use ISO 8601 date format

### ISSUE THREAD

**Issue by msm-** [distributedweaknessfiling/DWF-Database#4]
The database currently uses MM-DD-YYYY (American style) dates. As a non-regional specific system,  it would be better to use YYYY-MM-DD format dates (ISO 8601).
This has the added bonus of being able to sort based on date without requiring a date-aware sort algorithm.

**Comment by kurtseifried** [comment]
I agree, this also has the nice side effect of sorting numerically nicely. I'll make this change this weekend and document it.

**Comment by kurtseifried** [comment]
Updated the data, and the consistency checker has test for this now. Just need to update docs.
