### ISSUE TITLE
adding details (fields) to DWF reports

### ISSUE THREAD

**Issue by genkicode** [distributedweaknessfiling/DWF-Database#6]
some fields with content from the title and also a description field could be added, to allow more detailed reporting and filtering, based on the 2016 and 2015 database (operational or just demonstration dummys ?) and information layout on cvedetails.com

before i thought of submitting this as an issue (because before, i only used issues for bugs), i submitted a changed DWF-Example.csv file with added fields and example content.

Added:
1. Vendor, Product and affected versions, which is difficult to search / filter in Fulltext Title
2. Description, a more detailed Description with links to sources
3. Vulnerabilit type, (f.e. gain access, dos, elevate priviledges, session hijacking etc.)
4. Confirmation status, progress of the confirmation of the reported vulnerability

Possible example for 1 DWF Number for multiple vulnerabilities in 1 product

other scoring options from cvedetails.com could be added for a better description of the vulnerabilities
Confidentiality Impact (Data Accessible) ,Integrity Impact (degree of system modification), Availability Impact (reduced performance, interruptions or dos), Access Complexity (external or internal access to compromise the system) . Authentication, Gained Access (If, what level)

**Comment by kurtseifried** [comment]
The database is strictly limited information, the data you describe will be hosted in the DWF-Database-Artifacts repo, the reason being that this information is to varied to define well within a standard database (different types of products need different things). The data you mention would ideally go into the json file such as: https://github.com/distributedweaknessfiling/DWF-Database-Artifacts/blob/master/DWF/2015/77000/DWF-2015-77000.json
