### ISSUE TITLE
Fields to include in DWF database

### ISSUE THREAD

**Issue by kurtseifried** [distributedweaknessfiling/DWF-Database#7]
Currently we include:

* DWF_ID (will change to CVE_ID most likely)
* DATE_ASSIGNED (date)
* DATE_PUBLIC (date)
* REQUESTER (email address)
* ASSIGNER (email address)
* REPLACED_BY (CVE #)
* VERSION (INT, sequential)
* LAST_UPDATE (date)
* STATE (not decided yet, e.g. "RESERVED", "ASSIGNED", "CONFIRMED", "REJECT" etc.)
* TITLE (text string)

I want to keep this database lightweight and put the "heavy" into the JSON files

Mitre seems to primarily use:
* CVE
* Description
* Note
* Notes
* Reference
* References
* Title
* URL
* Vulnerability

NVD has mostly the same as Mitre but also:
* CVSS score (v2)
* CPE
* CWE

Next action step: confirm various database formats for Mitre CVE, NVD CVE and others (e.g. IBM X-Force?).

**Comment by sbunify** [comment]
CVSS and Severity:
I would put both CVSSv2 and CVSSv3 into the Json files.
The master database however should include a severity using the most well-known classification (critical / high or important / medium or moderate / low).
I am aware these ratings risk to be biased in one or the other direction - and of course there may be different severities and CVSS values for the same vulnerability (in the context of different software) but this needs to be sorted out in the individual details/advisories, i.e. in the json files.

**Comment by zmanion** [comment]
Agree that CVSS (and any other non-essential information) goes in JSON files and is optional. Philosophically, I recommend DWF focus narrowly on the information needed to identify a vulnerability, and let any further analysis (severity, CPE, CWE, etc) happen downstream. Fine to support optional further analysis in the JSON file/artifacts.

**Comment by zmanion** [comment]
I'd like to know others' thoughts on this idea too: Artifacts (at least the JSON file with at least one reference) *must* be included. An assignment can happen first, but once the vulnerability is public, the JSON file must be added. Stale assignments (assignments lacking JSON files with references) are removed or marked a certain way after N days?

**Comment by kurtseifried** [comment]
I'd rather have CVEs without JSON then no CVEs, worst case it means we have assigned CVEs that aren't in use. They either turn up eventually or we just ignore them (much like the current situation with 1000+ CVE's assigned by Red Hat and not in the MITRE database). Closing for now, we can also discuss this at the CVE summit.
